import org.gradle.accessors.dm.LibrariesForLibs

plugins {
    id("waystones.base")
    id("com.github.gmazzo.buildconfig")
}

val libs = extensions.getByName<LibrariesForLibs>("libs")

buildConfig {
    generateAtSync = true
    documentation.set("Generated by BuildConfig plugin, do not edit")
    packageName("xyz.atrius.waystones.autogenerated")
    className("WaystoneDependencyVersions")
    useKotlinOutput()
    buildConfigField("kotlinVersion", libs.kotlin.stdlib.get().version)
    buildConfigField("koinVersion", libs.koin.core.get().version)
    buildConfigField("arrowVersion", libs.arrow.core.get().version)
    buildConfigField("flywayVersion", libs.flyway.core.get().version)
    buildConfigField("sqliteVersion", libs.sqlite.jdbc.get().version)
    buildConfigField("mysqlVersion", libs.mysql.connector.get().version)
}
