name: Validate Flyway Sqlite
on:
  pull_request:
    paths:
      - 'src/main/resources/db/migration/common/**'
      - 'src/main/resources/db/migration/sqlite/**'
    branches:
      - main

env:
  DB_URL: 'jdbc:sqlite:./waystones.db'
  DB_NAME: waystones
  DB_TYPE: "sqlite"

permissions:
  contents: read

jobs:
  validate-flyway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
      - name: Test Flyway Migrations (SQLite)
        run: |-
          ./gradlew flywayClean flywayValidate flywayMigrate
