name: Code change pipeline

on:
  pull_request:
    paths:
      - 'src/main/kotlin/**'
      - 'src/test/kotlin/**'
      - 'src/main/resources/**'
      - 'src/test/resources/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - '.github/workflows/pr-pipeline.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
      - name: Build Project
        run: |-
          ./gradlew assemble
      - name: Check Project
        run: |-
          ./gradlew check
