name: Publish Plugin Snapshot
on:
  push:
    branches:
      - master

jobs:
  publish-hangar:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v4
      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew
      - name: Publish Hangar Snapshot
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: ./gradlew build publishWaystonesSnapshotPublicationToHangar --stacktrace

  publish-modrinth:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v4
      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew
      - name: Publish Modrinth Snapshot
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew build modrinth