name: Publish Plugin Snapshot
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'src/main/**'
      - 'gradle.properties'

permissions:
  contents: read

jobs:
  publish-hangar:
    if: ${{ github.actor != 'github-actions[bot]' && !startsWith(github.event.head_commit.message, 'chore(release)') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
      - name: Publish Hangar Snapshot
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: ./gradlew build publishWaystonesSnapshotPublicationToHangar --no-configuration-cache --stacktrace

  publish-modrinth:
    if: ${{ github.actor != 'github-actions[bot]' && !startsWith(github.event.head_commit.message, 'chore(release)') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
      - name: Publish Modrinth Snapshot
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew build modrinth --no-configuration-cache
